
CREATE TABLE DIM_TIEMPO(
	ID_TIEMPO INT PRIMARY KEY,
	ANNIO INT NOT NULL,
	TRIMESTER INT NOT NULL,
	MES INT NOT NULL,
	DIA INT NOT NULL
);

CREATE TABLE DIM_CLIENTE(
	ID_CLIENTE INT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	CIUDAD VARCHAR(50) NOT NULL,
	PAIS VARCHAR(50) NOT NULL
);

CREATE TABLE DIM_PROVEEDOR(
	ID_CLIENTE INT NOT NULL,
	ID_PROVEEDOR INT PRIMARY KEY,
	NOMBRECOMPANIA VARCHAR(50) NOT NULL,
	PAIS VARCHAR(50) NOT NULL
);

CREATE TABLE DIM_EMPLEADO(
	ID_EMPLEADO INT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL
);

CREATE TABLE DIM_PRODUCTO(
	ID_PRODUCTO INT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	CATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE H_PEDIDO(
	ID_PRODUCTO INT NOT NULL,
	ID_TIEMPO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	ID_EMPLEADO INT NOT NULL,
	PRECIO FLOAT NOT NULL,
	CANTIDAD INT NOT NULL,
	CONSTRAINT H_PK PRIMARY KEY (ID_PRODUCTO, ID_TIEMPO, ID_CLIENTE, ID_PROVEEDOR, ID_EMPLEADO),
	CONSTRAINT PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES DIM_PRODUCTO(ID_PRODUCTO),
	CONSTRAINT TIEMPO_FK FOREIGN KEY (ID_TIEMPO) REFERENCES DIM_TIEMPO(ID_TIEMPO),
	CONSTRAINT CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
	CONSTRAINT PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES DIM_PROVEEDOR(ID_PROVEEDOR),
	CONSTRAINT EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES DIM_EMPLEADO(ID_EMPLEADO)
)