CREATE TABLE DIM_EMPLEADO(
	DEPARTMENT_NAME VARCHAR(100) NOT NULL,
	EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PHONE_NUMBER VARCHAR(100) NOT NULL,
	JOB_TITLE VARCHAR(100) NOT NULL,
)

CREATE TABLE FECHA(
	FECHA_ID INT NOT NULL PRIMARY KEY,
	HIRE_DATE DATE NOT NULL
);

CREATE TABLE DIM_TIEMPO(
	FECHA_ID INT NOT NULL PRIMARY KEY,
	ANIO INT NOT NULL,
	TRIMESTRE INT NOT NULL,
	MES INT NOT NULL,
	HIRE_DATE DATE NOT NULL
);

CREATE TABLE HECHOS_HR(
	FECHA_ID INT,
	EMPLOYEE_ID INT,
	SALARY DOUBLE,
	COMMISION_PCT
)