CREATE DATABASE G3_PRACTICA2 

USE DATABASE G3_PRACTICA2


CREATE TABLE DIM_TIEMPO(
	FECHA_ID INT NOT NULL PRIMARY KEY,
	ANIO INT NOT NULL,
	TRIMESTRE INT NOT NULL,
	MES INT NOT NULL,
	DIA INT NOT NULL,
	OrderDate DATE NOT NULL
);

CREATE TABLE DIM_PRODUCTO(
	ProductID INT NOT NULL PRIMARY KEY,
	ProductName VARCHAR(100) NOT NULL,
	CategoryName VARCHAR(100) NOT NULL
)

CREATE TABLE DIM_CLIENTE(
	CustomerID NCHAR(5) NOT NULL PRIMARY KEY,
	City VARCHAR(100) NOT NULL,
	Country VARCHAR(100) NOT NULL
);

CREATE TABLE H_ORDENES(
	FECHA_ID INT NOT NULL,
	ProductID INT NOT NULL,
	CustomerID INT NOT NULL,
	UnitPrice MONEY NOT NULL,
	Quantity SMALLINT NOT NULL,
	Discount REAL NOT NULL
)